# Prepare Chicago Crime Data for a GitHub Repository

- Original Notebook Source: https://github.com/coding-dojo-data-science/preparing-chicago-crime-data
- Updated 11/17/22

>- This notebook will process a "Crimes - 2001 to Preset.csv" crime file in your Downloads folder and save it as smaller .csv's in a new "Data/Chicago/" folder inside this notebook's folder/repo.

# INSTRUCTIONS

- 1) Go to the Chicago Data Portal's page for ["Crimes - 2001 to Preset"](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2).

- 2) Click on the Export button on the top right and select CSV. 
    - Save the file to your Downloads folder instead of your repository. **The file is too big for a repository.**
    
    
    
- 3) Wait for the full file to download. 
    - It is very large (over >1.7GB and may take several minutes to fully download.)
    
    
- 4) Once the download is complete, change `RAW_FILE` variable below to match the filepath to the downloaded file.

## ðŸš¨ Set the correct `RAW_FILE` path

- The cell below will attempt to check your Downloads folder for any file with a name that contains "Crimes_-_2001_to_Present".
    - If you know the file path already, you can skip the next cell and just manually set the RAW_FILE variable in the following code cell.

In [1]:
## Run the cell below to attempt to programmatically find your crime file
import os,glob

## Getting the home folder from environment variables
home_folder = os.environ['HOME']
# print("- Your Home Folder is: " + home_folder)

## Check for downloads folder
if 'Downloads' in os.listdir(home_folder):
    
    
    # Print the Downloads folder path
    dl_folder = os.path.abspath(os.path.join(home_folder,'Downloads'))
    print(f"- Your Downloads folder is '{dl_folder}/'\n")
    
    ## checking for crime files using glob
    crime_files = sorted(glob.glob(dl_folder+'/**/Crimes_-_2001_to_Present*',recursive=True))
    
    # If more than 
    if len(crime_files)==1:
        RAW_FILE = crime_files[0]
        
    elif len(crime_files)>1:
        print('[i] The following files were found:')
        
        for i, fname in enumerate(crime_files):
            print(f"\tcrime_files[{i}] = '{fname}'")
        print(f'\n- Please fill in the RAW_FILE variable in the code cell below with the correct filepath.')

else:
    print(f'[!] Could not programmatically find your downloads folder.')
    print('- Try using Finder (on Mac) or File Explorer (Windows) to navigate to your Downloads folder.')

- Your Downloads folder is 'C:\Users\spart\Downloads/'

In [4]:
## (Required) MAKE SURE TO CHANGE THIS VARIABLE TO MATCH YOUR LOCAL FILE NAME
RAW_FILE = "Crimes_-_2001_to_Present.csv" #(or slice correct index from the crime_files list)

if RAW_FILE == "Crimes_-_2001_to_Present.csv":
	raise Exception("You must update the RAW_FILE variable to match your local filepath.")
	
RAW_FILE

NameError: name 'pd' is not defined

In [5]:
## (Optional) SET THE FOLDER FOR FINAL FILES
OUTPUT_FOLDER = 'Data/Chicago/'
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# ðŸ”„ Full Workflow

- Now that your RAW_FILE variable is set either:
    - On the toolbar, click on the Kernel menu > "Restart and Run All".
    - OR click on this cell first, then on the toolbar click on the "Cell" menu > "Run All Below"

In [6]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format',lambda x: f"{x:,.2f}")

In [7]:
chicago_full = pd.read_csv(RAW_FILE)
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,924,9.00,12.00,61.00,08B,"1,165,074.00","1,875,917.00",2015,02/10/2018 03:50:01 PM,41.82,-87.67,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,1511,15.00,29.00,25.00,06,"1,138,875.00","1,904,869.00",2015,02/10/2018 03:50:01 PM,41.90,-87.77,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,631,6.00,8.00,44.00,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,1412,14.00,35.00,21.00,18,"1,152,037.00","1,920,384.00",2015,02/10/2018 03:50:01 PM,41.94,-87.72,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,1522,15.00,28.00,25.00,08A,"1,141,706.00","1,900,086.00",2015,02/10/2018 03:50:01 PM,41.88,-87.76,"(41.881903443, -87.755121152)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3167118,4182400,HL498386,07/21/2005 11:10:00 AM,076XX S CICERO AVE,0860,THEFT,RETAIL THEFT,DEPARTMENT STORE,True,False,833,8.00,13.00,65.00,06,"1,145,727.00","1,853,720.00",2005,02/28/2018 03:56:25 PM,41.75,-87.74,"(41.754592961, -87.741528537)"
3167119,4182401,HL508996,06/14/2005 09:00:00 AM,100XX W OHARE ST,1206,DECEPTIVE PRACTICE,"THEFT BY LESSEE,MOTOR VEH",OTHER,True,False,1651,16.00,41.00,76.00,11,"1,100,658.00","1,934,241.00",2005,02/28/2018 03:56:25 PM,41.98,-87.91,"(41.976290414, -87.905227221)"
3167120,4182403,HL516862,07/30/2005 12:00:00 AM,086XX S WOOD ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,614,6.00,18.00,71.00,14,"1,165,851.00","1,847,489.00",2005,02/28/2018 03:56:25 PM,41.74,-87.67,"(41.737090659, -87.667956226)"
3167121,4182404,HL513737,06/16/2005 05:00:00 PM,015XX E 83RD ST,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,412,4.00,8.00,45.00,06,"1,187,794.00","1,850,251.00",2005,02/28/2018 03:56:25 PM,41.74,-87.59,"(41.744176204, -87.587476663)"
3167122,4182405,HL515798,07/29/2005 09:00:00 AM,020XX N SEDGWICK ST,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,1814,18.00,43.00,7.00,05,"1,173,262.00","1,913,873.00",2005,02/28/2018 03:56:25 PM,41.92,-87.64,"(41.919093849, -87.638838453)"

In [9]:
# explicitly setting the format to speed up pd.to_datetime
date_format = "%m/%d/%Y %H:%M:%S %p"


### Demonstrating/testing date_format
example = chicago_full.loc[0,'Date']
display(example)
pd.to_datetime(example,format=date_format)

'09/05/2015 01:30:00 PM'

Timestamp('2015-09-05 01:30:00')

In [10]:
# this cell can take up to 1 min to run
chicago_full['Datetime'] = pd.to_datetime(chicago_full['Date'], format=date_format)
chicago_full = chicago_full.sort_values('Datetime')
chicago_full = chicago_full.set_index('Datetime')
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
Datetime,,,,,,,,,,,,,,,,,,,,,,
2001-01-01 01:00:00,1330412,G026686,01/01/2001 01:00:00 AM,019XX N HALSTED ST,0820,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,NaN,06,"1,170,604.00","1,913,228.00",2001,08/17/2015 03:03:40 PM,41.92,-87.65,"(41.917382588, -87.648623098)"
2001-01-01 01:00:00,1312557,G001203,01/01/2001 01:00:00 PM,109XX S MICHIGAN AV,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,513,5.00,NaN,NaN,07,"1,178,895.00","1,832,264.00",2001,08/17/2015 03:03:40 PM,41.70,-87.62,"(41.695024578, -87.620628832)"
2001-01-01 01:00:00,1310741,G001135,01/01/2001 01:00:00 PM,047XX N ELSTON AV,0460,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,1722,17.00,NaN,NaN,08B,"1,145,613.00","1,931,427.00",2001,08/17/2015 03:03:40 PM,41.97,-87.74,"(41.96783306, -87.739978195)"
2001-01-01 01:00:00,1315987,G001152,01/01/2001 01:00:00 AM,009XX N HUDSON AV,1310,CRIMINAL DAMAGE,TO PROPERTY,CHA APARTMENT,False,False,1823,18.00,NaN,NaN,14,"1,173,036.00","1,906,862.00",2001,08/17/2015 03:03:40 PM,41.90,-87.64,"(41.899860332, -87.63987705)"
2001-01-01 01:00:00,1312658,G004147,01/01/2001 01:00:00 AM,040XX W CORTLAND ST,0460,BATTERY,SIMPLE,STREET,False,False,2534,25.00,NaN,NaN,08B,"1,149,393.00","1,912,364.00",2001,08/17/2015 03:03:40 PM,41.92,-87.73,"(41.915449949, -87.726575474)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27 05:30:00,12934648,JF524928,12/27/2022 05:30:00 PM,028XX E 93RD ST,0810,THEFT,OVER $500,RESIDENCE,False,False,423,4.00,7.00,48.00,06,"1,196,398.00","1,843,834.00",2022,01/03/2023 03:56:06 PM,41.73,-87.56,"(41.726358457, -87.556163641)"
2022-12-27 06:00:00,12938871,JG100725,12/27/2022 06:00:00 PM,021XX W CULLERTON ST,0810,THEFT,OVER $500,RESIDENCE,False,False,1234,12.00,25.00,31.00,06,"1,162,432.00","1,890,387.00",2022,01/03/2023 03:56:06 PM,41.85,-87.68,"(41.854880086, -87.679286699)"
2022-12-27 07:47:00,12934441,JF524539,12/27/2022 07:47:00 PM,052XX S CALUMET AVE,041A,BATTERY,AGGRAVATED - HANDGUN,STREET,False,False,231,2.00,3.00,40.00,04B,"1,179,370.00","1,870,429.00",2022,01/03/2023 03:56:06 PM,41.80,-87.62,"(41.799742941, -87.61772761)"
2022-12-27 08:00:00,12933690,JF523732,12/27/2022 08:00:00 AM,068XX S CRANDON AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,331,3.00,5.00,43.00,07,"1,192,500.00","1,860,135.00",2022,01/03/2023 03:56:06 PM,41.77,-87.57,"(41.77118547, -87.569912302)"
2022-12-27 10:38:00,12934459,JF524673,12/27/2022 10:38:00 PM,057XX S SPAULDING AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,822,8.00,23.00,63.00,08A,"1,155,365.00","1,866,293.00",2022,01/03/2023 03:56:06 PM,41.79,-87.71,"(41.788907837, -87.705871593)"

In [11]:
(chicago_full.isna().sum()/len(chicago_full)).round(2)

ID                     0.00
Case Number            0.00
Date                   0.00
Block                  0.00
IUCR                   0.00
Primary Type           0.00
Description            0.00
Location Description   0.00
Arrest                 0.00
Domestic               0.00
Beat                   0.00
District               0.00
Ward                   0.19
Community Area         0.18
FBI Code               0.00
X Coordinate           0.00
Y Coordinate           0.00
Year                   0.00
Updated On             0.00
Latitude               0.00
Longitude              0.00
Location               0.00
dtype: float64

## Separate the Full Dataset by Years

In [12]:
# save the years for every crime
chicago_full["Year"] = chicago_full.index.year
chicago_full["Year"] = chicago_full["Year"].astype(str)
chicago_full["Year"].value_counts()

2001    466716
2003    460900
2002    459235
2004    456587
2016    261926
2017    261379
2018    261012
2005    236222
2015    162180
2019    116560
2020     17247
2021      2551
2014      1465
2022      1235
2013       638
2012       412
2011       264
2010       218
2009       127
2008       103
2006        77
2007        69
Name: Year, dtype: int64

In [13]:
## Dropping unneeded columns to reduce file size
drop_cols = ["X Coordinate","Y Coordinate", "Community Area","FBI Code",
             "Case Number","Updated On",'Block','Location','IUCR']

In [14]:
# save final df
chicago_final = chicago_full.drop(columns=drop_cols).sort_index()#.reset_index()
chicago_final

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Year,Latitude,Longitude
Datetime,,,,,,,,,,,,,
2001-01-01 01:00:00,1330412,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,2001,41.92,-87.65
2001-01-01 01:00:00,1312557,01/01/2001 01:00:00 PM,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,513,5.00,NaN,2001,41.70,-87.62
2001-01-01 01:00:00,1310741,01/01/2001 01:00:00 PM,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,1722,17.00,NaN,2001,41.97,-87.74
2001-01-01 01:00:00,1315987,01/01/2001 01:00:00 AM,CRIMINAL DAMAGE,TO PROPERTY,CHA APARTMENT,False,False,1823,18.00,NaN,2001,41.90,-87.64
2001-01-01 01:00:00,1312658,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,STREET,False,False,2534,25.00,NaN,2001,41.92,-87.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27 05:30:00,12934648,12/27/2022 05:30:00 PM,THEFT,OVER $500,RESIDENCE,False,False,423,4.00,7.00,2022,41.73,-87.56
2022-12-27 06:00:00,12938871,12/27/2022 06:00:00 PM,THEFT,OVER $500,RESIDENCE,False,False,1234,12.00,25.00,2022,41.85,-87.68
2022-12-27 07:47:00,12934441,12/27/2022 07:47:00 PM,BATTERY,AGGRAVATED - HANDGUN,STREET,False,False,231,2.00,3.00,2022,41.80,-87.62
2022-12-27 08:00:00,12933690,12/27/2022 08:00:00 AM,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,331,3.00,5.00,2022,41.77,-87.57
2022-12-27 10:38:00,12934459,12/27/2022 10:38:00 PM,ASSAULT,SIMPLE,APARTMENT,False,True,822,8.00,23.00,2022,41.79,-87.71

In [15]:
chicago_final.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3167123 entries, 2001-01-01 01:00:00 to 2022-12-27 10:38:00
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Date                  object
 2   Primary Type          object
 3   Description           object
 4   Location Description  object
 5   Arrest                bool
 6   Domestic              bool
 7   Beat                  int64
 8   District              float64
 9   Ward                  float64
 10  Year                  object
 11  Latitude              float64
 12  Longitude             float64
dtypes: bool(2), float64(4), int64(2), object(5)
memory usage: 296.0+ MB

In [16]:
chicago_final.memory_usage(deep=True).astype(float)

Index                   25,336,984.00
ID                      25,336,984.00
Date                   250,202,717.00
Primary Type           212,237,220.00
Description            230,558,350.00
Location Description   215,912,747.00
Arrest                   3,167,123.00
Domestic                 3,167,123.00
Beat                    25,336,984.00
District                25,336,984.00
Ward                    25,336,984.00
Year                   193,194,503.00
Latitude                25,336,984.00
Longitude               25,336,984.00
dtype: float64

In [17]:
# unique # of year bins
year_bins = chicago_final['Year'].astype(str).unique()
year_bins

array(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022'], dtype=object)

In [18]:
FINAL_DROP = ['Datetime','Year']#,'Location Description']

In [19]:
## set save location 

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
print(f"[i] Saving .csv's to {OUTPUT_FOLDER}")
## loop through years
for year in year_bins:
    
    ## save temp slices of dfs to save.
    temp_df = chicago_final.loc[ year]
    temp_df = temp_df.reset_index(drop=False)
    temp_df = temp_df.drop(columns=FINAL_DROP)

    # save as csv to output folder
    fname_temp = f"{OUTPUT_FOLDER}Chicago-Crime_{year}.csv"#.gz
    temp_df.to_csv(fname_temp,index=False)

    print(f"- Succesfully saved {fname_temp}")

[i] Saving .csv's to Data/Chicago/
- Succesfully saved Data/Chicago/Chicago-Crime_2001.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2002.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2003.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2004.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2005.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2006.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2007.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2008.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2009.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2010.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2011.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2012.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2013.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2014.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2015.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2016.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2017.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2018.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2019.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2020.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2021.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2022.csv

In [20]:
saved_files = sorted(glob.glob(OUTPUT_FOLDER+'*.*csv'))
saved_files

['Data/Chicago\\Chicago-Crime_2001.csv',
 'Data/Chicago\\Chicago-Crime_2002.csv',
 'Data/Chicago\\Chicago-Crime_2003.csv',
 'Data/Chicago\\Chicago-Crime_2004.csv',
 'Data/Chicago\\Chicago-Crime_2005.csv',
 'Data/Chicago\\Chicago-Crime_2006.csv',
 'Data/Chicago\\Chicago-Crime_2007.csv',
 'Data/Chicago\\Chicago-Crime_2008.csv',
 'Data/Chicago\\Chicago-Crime_2009.csv',
 'Data/Chicago\\Chicago-Crime_2010.csv',
 'Data/Chicago\\Chicago-Crime_2011.csv',
 'Data/Chicago\\Chicago-Crime_2012.csv',
 'Data/Chicago\\Chicago-Crime_2013.csv',
 'Data/Chicago\\Chicago-Crime_2014.csv',
 'Data/Chicago\\Chicago-Crime_2015.csv',
 'Data/Chicago\\Chicago-Crime_2016.csv',
 'Data/Chicago\\Chicago-Crime_2017.csv',
 'Data/Chicago\\Chicago-Crime_2018.csv',
 'Data/Chicago\\Chicago-Crime_2019.csv',
 'Data/Chicago\\Chicago-Crime_2020.csv',
 'Data/Chicago\\Chicago-Crime_2021.csv',
 'Data/Chicago\\Chicago-Crime_2022.csv']

In [21]:
## create a README.txt for the zip files
readme = """Source URL: 
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])
"""
print(readme)


with open(f"{OUTPUT_FOLDER}README.txt",'w') as f:
    f.write(readme)

Source URL:
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])

## Confirmation

- Follow the example usage above to test if your files were created successfully.

In [22]:
# get list of files from folder
crime_files = sorted(glob.glob(OUTPUT_FOLDER+"*.csv"))
df = pd.concat([pd.read_csv(f) for f in crime_files])
df

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Latitude,Longitude
0,1330412,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,41.92,-87.65
1,1312557,01/01/2001 01:00:00 PM,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,513,5.00,NaN,41.70,-87.62
2,1310741,01/01/2001 01:00:00 PM,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,1722,17.00,NaN,41.97,-87.74
3,1315987,01/01/2001 01:00:00 AM,CRIMINAL DAMAGE,TO PROPERTY,CHA APARTMENT,False,False,1823,18.00,NaN,41.90,-87.64
4,1312658,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,STREET,False,False,2534,25.00,NaN,41.92,-87.73
...,...,...,...,...,...,...,...,...,...,...,...,...
1230,12934648,12/27/2022 05:30:00 PM,THEFT,OVER $500,RESIDENCE,False,False,423,4.00,7.00,41.73,-87.56
1231,12938871,12/27/2022 06:00:00 PM,THEFT,OVER $500,RESIDENCE,False,False,1234,12.00,25.00,41.85,-87.68
1232,12934441,12/27/2022 07:47:00 PM,BATTERY,AGGRAVATED - HANDGUN,STREET,False,False,231,2.00,3.00,41.80,-87.62
1233,12933690,12/27/2022 08:00:00 AM,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,331,3.00,5.00,41.77,-87.57
1234,12934459,12/27/2022 10:38:00 PM,ASSAULT,SIMPLE,APARTMENT,False,True,822,8.00,23.00,41.79,-87.71

In [23]:
years = df['Date'].map(lambda x: x.split()[0].split('/')[-1])
years.value_counts().sort_index()

2001    466716
2002    459235
2003    460900
2004    456587
2005    236222
2006        77
2007        69
2008       103
2009       127
2010       218
2011       264
2012       412
2013       638
2014      1465
2015    162180
2016    261926
2017    261379
2018    261012
2019    116560
2020     17247
2021      2551
2022      1235
Name: Date, dtype: int64

## Summary

- The chicago crime dataset has now been saved to your repository as csv files. 
- You should save your notebook, commit your work and push to GitHub using GitHub desktop.